ROLES = ['carry', 'ganker', 'jungler', 'pusher', 'disabler', 'initiator', 'offlaner', 'support']
REGIONS = ['US West', 'US East', 'EU West', 'EU East', 'Russia', 'South America', 'SE Asia', 'Australia']
REGIONS_LABELS = ['uswest', 'useast', 'euwest', 'eueast', 'russia', 'southamerica', 'seasia', 'australia']
AVAILABILITY = ['Weekends only', 'Any day', 'Evenings only', 'Any time']
AVAILABILITY_LABELS = ['weekends', 'anyday', 'evenings', 'anytime']
HEROES = [
    "Abaddon",
    "Alchemist",
    "Ancient Apparition",
    "Anti-Mage",
    "Arc Warden",
    "Axe",
    "Bane",
    "Batrider",
    "Beastmaster",
    "Bloodseeker",
    "Bounty Hunter",
    "Brewmaster",
    "Bristleback",
    "Broodmother",
    "Centaur Warrunner ",
    "Chaos Knight",
    "Chen",
    "Clinkz",
    "Clockwerk",
    "Crystal Maiden",
    "Dark Seer",
    "Dazzle",
    "Death Prophet",
    "Disruptor",
    "Doom Bringer",
    "Dragon Knight",
    "Drow Ranger",
    "Earth Spirit",
    "Earthshaker",
    "Elder Titan",
    "Ember Spirit",
    "Enchantress",
    "Enigma",
    "Faceless Void",
    "Goblin Techies",
    "Gyrocopter",
    "Huskar",
    "Invoker",
    "Io",
    "Jakiro",
    "Juggernaut",
    "Keeper of the Light",
    "Kunkka",
    "Legion Commander",
    "Leshrac",
    "Lich",
    "Lifestealer",
    "Lina",
    "Lion",
    "Lone Druid",
    "Luna",
    "Lycanthrope",
    "Magnus",
    "Medusa",
    "Meepo",
    "Mirana",
    "Morphling",
    "Naga Siren",
    "Nature's Prophet",
    "Necrophos",
    "Night Stalker",
    "Nyx Assassin",
    "Ogre Magi",
    "Omniknight",
    "Oracle",
    "Outworld Devourer",
    "Phantom Assassin",
    "Phantom Lancer",
    "Phoenix",
    "Pit Lord",
    "Puck",
    "Pudge",
    "Pugna",
    "Queen of Pain",
    "Razor",
    "Riki",
    "Rubick",
    "Sand King",
    "Shadow Demon",
    "Shadow Fiend",
    "Shadow Shaman",
    "Silencer",
    "Skywrath Mage",
    "Slardar",
    "Slark",
    "Sniper",
    "Soul Keeper",
    "Spectre",
    "Spirit Breaker",
    "Storm Spirit",
    "Sven",
    "Templar Assassin",
    "Tidehunter",
    "Timbersaw",
    "Tinker",
    "Tiny",
    "Treant Protector",
    "Troll Warlord",
    "Tusk",
    "Undying",
    "Ursa",
    "Vengeful Spirit",
    "Venomancer",
    "Viper",
    "Visage",
    "Warlock",
    "Weaver",
    "Windranger",
    "Winter Wyvern",
    "Witch Doctor",
    "Wraith King",
    "Zeus"
]
