ROLES = ['carry', 'ganker', 'jungler', 'pusher', 'disabler', 'initiator', 'offlaner', 'support']
REGIONS = ['US West', 'US East', 'EU West', 'EU East', 'Russia', 'South America', 'SE Asia', 'Australia']
REGIONS_LABELS = ['uswest', 'useast', 'euwest', 'eueast', 'russia', 'southamerica', 'seasia', 'australia']
AVAILABILITY = ['weekends', 'anyday', 'evenings', 'anytime']
AVAILABILITY_LABELS = ['Weekends only', 'Any day', 'Evenings only', 'Any time']
MENTORING = ['individual', 'team', 'spectating', 'together', 'analysing', 'questions', 'voicechat', 'textchat']
MENTORING_LABELS = ['individual mentoring', 'team monitoring', 'mentoring while spectating', 'mentoring while playing together', 'anaylsing replies', 'general questions & answers', 'voice chat', 'text chat']
HEROES = [
    "Abaddon",
    "Alchemist",
    "Ancient Apparition",
    "Anti-Mage",
    "Arc Warden",
    "Axe",
    "Bane",
    "Batrider",
    "Beastmaster",
    "Bloodseeker",
    "Bounty Hunter",
    "Brewmaster",
    "Bristleback",
    "Broodmother",
    "Centaur Warrunner ",
    "Chaos Knight",
    "Chen",
    "Clinkz",
    "Clockwerk",
    "Crystal Maiden",
    "Dark Seer",
    "Dazzle",
    "Death Prophet",
    "Disruptor",
    "Doom Bringer",
    "Dragon Knight",
    "Drow Ranger",
    "Earth Spirit",
    "Earthshaker",
    "Elder Titan",
    "Ember Spirit",
    "Enchantress",
    "Enigma",
    "Faceless Void",
    "Goblin Techies",
    "Gyrocopter",
    "Huskar",
    "Invoker",
    "Io",
    "Jakiro",
    "Juggernaut",
    "Keeper of the Light",
    "Kunkka",
    "Legion Commander",
    "Leshrac",
    "Lich",
    "Lifestealer",
    "Lina",
    "Lion",
    "Lone Druid",
    "Luna",
    "Lycanthrope",
    "Magnus",
    "Medusa",
    "Meepo",
    "Mirana",
    "Morphling",
    "Naga Siren",
    "Nature's Prophet",
    "Necrophos",
    "Night Stalker",
    "Nyx Assassin",
    "Ogre Magi",
    "Omniknight",
    "Oracle",
    "Outworld Devourer",
    "Phantom Assassin",
    "Phantom Lancer",
    "Phoenix",
    "Pit Lord",
    "Puck",
    "Pudge",
    "Pugna",
    "Queen of Pain",
    "Razor",
    "Riki",
    "Rubick",
    "Sand King",
    "Shadow Demon",
    "Shadow Fiend",
    "Shadow Shaman",
    "Silencer",
    "Skywrath Mage",
    "Slardar",
    "Slark",
    "Sniper",
    "Soul Keeper",
    "Spectre",
    "Spirit Breaker",
    "Storm Spirit",
    "Sven",
    "Templar Assassin",
    "Tidehunter",
    "Timbersaw",
    "Tinker",
    "Tiny",
    "Treant Protector",
    "Troll Warlord",
    "Tusk",
    "Undying",
    "Ursa",
    "Vengeful Spirit",
    "Venomancer",
    "Viper",
    "Visage",
    "Warlock",
    "Weaver",
    "Windranger",
    "Winter Wyvern",
    "Witch Doctor",
    "Wraith King",
    "Zeus"
]

HEROES_HASH = {
    "abaddon": "Abaddon",
    "alchemist": "Alchemist",
    "ancient_apparition": "Ancient Apparition",
    "anti-mage": "Anti-Mage",
    "arc_warden": "Arc Warden",
    "axe": "Axe",
    "bane": "Bane",
    "batrider": "Batrider",
    "beastmaster": "Beastmaster",
    "bloodseeker": "Bloodseeker",
    "bounty_hunter": "Bounty Hunter",
    "brewmaster": "Brewmaster",
    "bristleback": "Bristleback",
    "broodmother": "Broodmother",
    "centaur_warrunner": "Centaur Warrunner",
    "chaos_knight": "Chaos Knight",
    "chen": "Chen",
    "clinkz": "Clinkz",
    "clockwerk": "Clockwerk",
    "crystal_maiden": "Crystal Maiden",
    "dark_seer": "Dark Seer",
    "dazzle": "Dazzle",
    "death_prophet": "Death Prophet",
    "disruptor": "Disruptor",
    "doom_bringer": "Doom Bringer",
    "dragon_knight": "Dragon Knight",
    "drow_ranger": "Drow Ranger",
    "earth_spirit": "Earth Spirit",
    "earthshaker": "Earthshaker",
    "elder_titan": "Elder Titan",
    "ember_spirit": "Ember Spirit",
    "enchantress": "Enchantress",
    "enigma": "Enigma",
    "faceless_void": "Faceless Void",
    "goblin_techies": "Goblin Techies",
    "gyrocopter": "Gyrocopter",
    "huskar": "Huskar",
    "invoker": "Invoker",
    "io": "Io",
    "jakiro": "Jakiro",
    "juggernaut": "Juggernaut",
    "keeper_of_the_light": "Keeper of the Light",
    "kunkka": "Kunkka",
    "legion_commander": "Legion Commander",
    "leshrac": "Leshrac",
    "lich": "Lich",
    "lifestealer": "Lifestealer",
    "lina": "Lina",
    "lion": "Lion",
    "lone_druid": "Lone Druid",
    "luna": "Luna",
    "lycanthrope": "Lycanthrope",
    "magnus": "Magnus",
    "medusa": "Medusa",
    "meepo": "Meepo",
    "mirana": "Mirana",
    "morphling": "Morphling",
    "naga_siren": "Naga Siren",
    "nature's_prophet": "Nature's Prophet",
    "necrophos": "Necrophos",
    "night_stalker": "Night Stalker",
    "nyx_assassin": "Nyx Assassin",
    "ogre_magi": "Ogre Magi",
    "omniknight": "Omniknight",
    "oracle": "Oracle",
    "outworld_devourer": "Outworld Devourer",
    "phantom_assassin": "Phantom Assassin",
    "phantom_lancer": "Phantom Lancer",
    "phoenix": "Phoenix",
    "pit_lord": "Pit Lord",
    "puck": "Puck",
    "pudge": "Pudge",
    "pugna": "Pugna",
    "queen_of_pain": "Queen of Pain",
    "razor": "Razor",
    "riki": "Riki",
    "rubick": "Rubick",
    "sand_king": "Sand King",
    "shadow_demon": "Shadow Demon",
    "shadow_fiend": "Shadow Fiend",
    "shadow_shaman": "Shadow Shaman",
    "silencer": "Silencer",
    "skywrath_mage": "Skywrath Mage",
    "slardar": "Slardar",
    "slark": "Slark",
    "sniper": "Sniper",
    "soul_keeper": "Soul Keeper",
    "spectre": "Spectre",
    "spirit_breaker": "Spirit Breaker",
    "storm_spirit": "Storm Spirit",
    "sven": "Sven",
    "templar_assassin": "Templar Assassin",
    "tidehunter": "Tidehunter",
    "timbersaw": "Timbersaw",
    "tinker": "Tinker",
    "tiny": "Tiny",
    "treant_protector": "Treant Protector",
    "troll_warlord": "Troll Warlord",
    "tusk": "Tusk",
    "undying": "Undying",
    "ursa": "Ursa",
    "vengeful_spirit": "Vengeful Spirit",
    "venomancer": "Venomancer",
    "viper": "Viper",
    "visage": "Visage",
    "warlock": "Warlock",
    "weaver": "Weaver",
    "windranger": "Windranger",
    "winter_wyvern": "Winter Wyvern",
    "witch_doctor": "Witch Doctor",
    "wraith_king": "Wraith King",
    "zeus": "Zeus"
}

SIGNUP_FORM = {
    'about': {},
    'day': {},
    'displayName': {},
    'email': {},
    'email2': {},
    'mentoring': {},
    'region': {},
    'role': {},
    'statistics': {},
    'steamId': {},
    'steamIdLink': {},
    'time': {},
    'topheroes': {}
}
