ROLES = ['carry', 'ganker', 'jungler', 'pusher', 'disabler', 'initiator', 'offlaner', 'support']
REGIONS = ['US West', 'US East', 'EU West', 'EU East', 'Russia', 'South America', 'SE Asia', 'Australia']
REGIONS_LABELS = ['uswest', 'useast', 'euwest', 'eueast', 'russia', 'southamerica', 'seasia', 'australia']
AVAILABILITY = ['Weekends only', 'Any day', 'Evenings only', 'Any time']
AVAILABILITY_LABELS = ['weekends', 'anyday', 'evenings', 'anytime']
